import mongoose from "mongoose";
import Player from "./models/Player";
import { mongo } from "./database";

let databaseConfig = new mongo();

async function conectBD(){
    const db = await mongoose.connect(`mongodb:\/\/${databaseConfig.host}/${databaseConfig.db}`);
    console.log("DB is connected to", db.connection.db.databaseName);
}

conectBD();

async function executeQuery() {
    /*  Description:
    In this block, a new document is created manually. Using the save() function,
    the document is inserted with the specifications defined previously before using the function.
    The _id field is defined manually, but it can also be assigned automatically.
    The _id field is a unique identifier for each document in the collection.
    If the _id is assigned manually, it is necessary to ensure that it is unique and does not repeat.
    If a document with the same _id already exists, an error will be thrown when trying to save it.
    However, if the _id is assigned automatically, it is possible to save as many documents as needed.
    The _id field is automatically generated by MongoDB and is guaranteed to be unique.
    */

    /* A brew example of how to create a new player object and save it to the database.
        const player = new Player({
        _id: "05411j",
        
        position:
        {
            x: 2.5,
            y: 5.5,
            z: 8.7,
        },

        rotation:
        {
            x: 2.5,
            y: 5.5,
            z: 8.7,
            w: 5.2
        } });

        await player.save();
        console.log(player);
    */


    const player = await Player.find({_id: " New player ID"}, {_id: 1, position: 1})
    if(player.length != 0)
    {
        console.log("There is an object");
        const player = await Player.findByIdAndUpdate("New player ID", 
        {position: { x: 1.5, y: 2.5, z: 1},
        rotation: { x: 1, y: 0, z: 1}},
        {new: true});
        console.log("Player updated");
        console.log(player);
    }
    else
    {
        console.log("There isn't an object");
        const player = new Player({
            _id: "New player ID",
            position: { x: 0.5, y: 1.5, z: 0},
            rotation: { x: 0, y: 0, z: 1}
        });
        await player.save();
        console.log(player);
        

    }
    
}

executeQuery();